version: '3.8'

networks:
  my-bridge-network:
    driver: bridge

services:
  web-service:
    image: registry.cn-hangzhou.aliyuncs.com/n1book/web-sql-2:latest
    ports:
      - '80:80'
    networks:
      - my-bridge-network

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    user: zap
    ports:
      - '8080:8080'
      - '8090:8090'
    networks:
      - my-bridge-network
    depends_on:
      - web-service
    command: zap-webswing.sh
