version: '3'
services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/n1book/web-unserialize:latest
    ports:
      - 80:80
    networks:
      - my-bridge-network

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    user: zap
    ports:
      - '8080:8080'
      - '8090:8090'
    networks:
      - my-bridge-network
    command: zap-webswing.sh

networks:
  my-bridge-network:
    driver: bridge
