version: '3.8'

networks:
  my-bridge-network:
    driver: bridge

services:
  ssti-vuln:
    image: registry.cn-hangzhou.aliyuncs.com/n1book/python-ssti
    container_name: ssti-vuln
    restart: always
    ports:
      - '8000:8000'
    networks:
      - my-bridge-network

  nginx:
    image: nginx:latest
    container_name: static-server
    volumes:
      - ./ctf:/usr/share/nginx/html
    ports:
      - 9090:80
    networks:
      - my-bridge-network
